travis:
  secure:
    BINSTAR_TOKEN: qft0CzOO/dcdR90xwyVlSCqdX7MBK5l2/9X58QgBBY1PipLNiGWazwabfMAHUfgH1SY6D/Trxu7vOuHBTEnQg6RkmDVrhGnLF1x4JvyzyeYzHuJhR+47kdnoPlwJb0vdbyW0R/nH5EkaWcaqvLzF4HNmmeI7mErOUtfYMVQ+UwRtL3Xiyfkjh0rup9oIPUsW8QgvJ0+37q639W3X7L+NWpR+LYv+fdCEL1BSG53PLO/8Cr2qiPTP22bSMlNTPbG+nPSDukD6fNJ/HUZQ6HQG0Mqsw/+05KRU66Uwsh1OxWM4NHGEEq1eI+gqIWQ+2/7CX13J9FTa5RfRJF0msiqZY4t+9qboSK9Z2BkC0UKM3tib8P9O9JS0LNvrRwAZKnuTyUfMGmr3fMBm9PEedTlyEeh5Y+mIfQRzt4v6JDJWVZ8btqmxzjzhB2Zvy8yItiXnz+UY0UNKv++CL/lCE/ej4b9gFGm2y6HxMsu/S5aQ9fvBZHRq/qAMtRA8XK9F0t8Z85oTRWVIqttppG4azE/2iF1kfrjZ8wZ/1d+YRn5U7qzFQRxACSX15nDTSOhOigXVS9TrJ4CVxJ6jjC5RN2bAOevugpnCcKbbvPW6t/ZV4vc1Ynd8HWRddRCjrTr4N3d4FleviGFy1BTwpXRq6igj8Z1XgZzvMqQ2kDqc9XvYMl0=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
